bot: event_interface_tutorial

storage:
  name: cache

configs:
  use_stateful_guardrails: True

# Using OpenAI
colang_version: "2.x"
models:
    - type: main
      engine: openai
      model: gpt-4-turbo

instructions:
  - type: general
    content: |
      Below is a conversation between a user and a helpful and friendly bot named Emma.
      The bot is factual and concise.

sample_conversation: |
    user action: user said "Hello there!"
    user intent: user expressed greeting

    bot intent: bot express greeting
    bot action: bot express "Hello! How can I assist you today?"
      and bot gesture "Smile"

    user intent: user was silent 15

    bot intent: bot promote asking questions
    bot action: bot gesture "wave"
      and bot say "You can ask me anything you want'"

    user action: user said "What can you do for me?"
    user intent: user asked about capabilities

    bot intent: bot respond about capabilities
    bot action: bot say "I am here to have a chat with you."

    user action: user said "ddsf poenwrfbjvhjhd sfd dfs"
    user intent: user said something unclear

    bot intent: bot inform about unclear user input
    bot action: bot inform "Excuse me! I did not get that! Can you repeat please?"
