fluent-bit:
  enable: true
  config:
    service: |
      [SERVICE]
          Daemon Off
          Flush {{ '{{' }} .Values.flush {{ '}}' }}
          Log_Level {{ '{{' }} .Values.logLevel {{ '}}' }}
          Parsers_File parsers.conf
          Parsers_File custom_parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port {{ '{{' }} .Values.metricsPort {{ '}}' }}
          Health_Check On

    ## https://docs.fluentbit.io/manual/pipeline/inputs
    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/*.log
          multiline.parser docker, cri
          Tag kube.*
          Mem_Buf_Limit 5MB
          Skip_Long_Lines On

      [INPUT]
          Name systemd
          Tag host.*
          Systemd_Filter _SYSTEMD_UNIT=kubelet.service
          Read_From_Tail On

    ## https://docs.fluentbit.io/manual/pipeline/filters
    filters: |
      [FILTER]
          Name kubernetes
          Match kube.*
          Merge_Log On
          Keep_Log Off
          K8S-Logging.Parser On
          K8S-Logging.Exclude On

      [FILTER]
          Name grep
          Match kube.*
          Exclude kubernetes_container_name fluent-bit

    ## https://docs.fluentbit.io/manual/pipeline/outputs
    outputs: |
      [OUTPUT]
          Name es
          Match kube.*
          Host tokkio-logging-es-cluster-master-headless
          # Logstash_Format On
          # Logstash_DateFormat %Y-%m-%d
          Index k8s-logs
          # Logstash_Prefix k8s
          Replace_Dots On
          # Type _doc
          Retry_Limit False
          Trace_Error On

      [OUTPUT]
          Name es
          Match host.*
          Host tokkio-logging-es-cluster-master-headless
          Logstash_Format On
          Logstash_Prefix node
          Replace_Dots On
          # Type _doc
          Retry_Limit False
          # Trace_Error On

      # [OUTPUT]
      #     Name stdout
      #     Match kube.*
      #     Format json
      #     Json_date_key timestamp
      #     Json_date_format iso8601

    ## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/upstream-servers
    ## This configuration is deprecated, please use `extraFiles` instead.
    upstream: {}

    ## https://docs.fluentbit.io/manual/pipeline/parsers
    customParsers: |
      [PARSER]
          Name docker_no_time
          Format json
          Time_Keep Off
          Time_Key time
          Time_Format %Y-%m-%dT%H:%M:%S.%L
