grpc_server:
  nvidia::rrt::BotRuntimeGrpc: # component type
    ip_address: "0.0.0.0"
    port_number: 50055
    virtual_assistant_num_instances: 30
    virtual_assistant_pipeline_idle_threshold_secs: 600
    virtual_assistant_pipeline_idle_handler_wakeup_rate_secs: 10

speech_pipeline_manager: # config name
  SpeechPipelineManager: # component name
    asr_idle_timeout_ms: 200000
    tts_eos_delay_ms: 2000

riva_asr:
  RivaASR:
    server: "localhost:50051"
    word_boost_file_path: "/workspace/config/asr_words_to_boost_conformer.txt"
    enable_profanity_filter: false

dialog_manager:
  DialogManager:
    # Default bot name and version to be used in speech mode
    bot_name: "jin"
    bot_version: "1"
    server: "http://localhost:9000"
    use_streaming: true

riva_tts:
  RivaTTS:
    server: "localhost:50051"
    voice_name: "English-US-RadTTS.Male-1"
    language: "en-US"
    ipa_dict: ""
    sample_rate: 44100
    chunk_duration_ms: 100
    audio_start_threshold_ms: 400
    send_audio_in_realtime: true

a2f_grpc:
    avatar_model: "/World/dragon_a2f/audio_player_streaming"
    server: "localhost:50051"
    rpc_timeout_ms: 300000

riva_logger:
  RivaLogger:
    data_dump_path: "/workspace/log"
    enable_logging: true