---
- hosts: all
  gather_facts: true
  tasks:
    - name: check if k8s secrets are empty of type Opaque
      loop: "{{ task_config.k8s_secrets }}"
      when:
        - task_config.k8s_secrets is defined
        - task_config.k8s_secrets | length > 0
        - item.type == "Opaque"
      include_tasks: tasks/k8s-secret-check-empty-opaque.yml

    - name: check if k8s secrets are empty of type dockerconfigjson
      loop: "{{ task_config.k8s_secrets }}"
      when:
        - task_config.k8s_secrets is defined
        - task_config.k8s_secrets | length > 0
        - item.type == "dockerconfigjson"
      include_tasks: tasks/k8s-secret-check-empty-dockerconfig.yml
