config:
  workers: 1
  timeout: 30

plugins:
  - name: prompt_former
    path: plugins/prompt_former.py
    parameters:

      # Default value of character personality
      jin:
        quality: 9
        toxicity: 0
        humour: 2
        creativity: 3
        violence: 0
        helpfulness: 2
        inappropriate: 0

      elara:
        quality: 9
        toxicity: 0
        humour: 2
        creativity: 7
        violence: 0
        helpfulness: 8
        inappropriate: 0