schema_version: '0.0.10'
name: '<replace-with-unique-name>'
spec:
  infra:
    csp: 'bm'
    backend: {}
    provider: {}
    configs:
      cns:
        # version: <replace-with-desired-cns-version-defaults-to-14.0>
        # git_ref: <replace-with-git-commit-hash-defaults-to-v24.11.2>
        override_values:
          cns_nvidia_driver: <replace-with-yes-or-no-yes-when-need-to-install-nvidia-driver-using-runfile>
          #gpu_driver_version: <replace-with-desired-gpu-driver-version>
      ssh_public_key: "{{ lookup('file', lookup('env', 'HOME') +'ssh-pub-key-path') }}"
      ssh_private_key_path: "{{ lookup('env', 'HOME') + 'ssh-pem-key-path' }}"
      additional_ssh_public_keys: []
      #turn_server_provider: '<one-of-allowed-implementation-coturn|twilio-defaults-to-coturn>'
      clusters:
        app:
          master:
            user: "{{ lookup('env', 'APP_HOST_SSH_USER', default=Undefined) }}"
            host: "{{ lookup('env', 'APP_HOST_IPV4_ADDR', default=Undefined) }}"
          ports:
            ui:
              port: 30111
              protocol: "https"
            api:
              port: 30888
              protocol: "https"
            grafana:
              port: 32300
            ace_configurator:
              port: 30180
          features:
            cns: true
            app: true
        turn:
          master:
            user: "{{ lookup('env', 'COTURN_HOST_SSH_USER', default=Undefined) }}"
            host: "{{ lookup('env', 'COTURN_HOST_IPV4_ADDR', default=Undefined) }}"
          features:
            coturn: true
  platform:
    # configs:
    #   foundational_chart_settings:
    #     k8s_namespace: '<replace-with-k8s-namespace-for-all-foundational-chart-to-deploy-defaults-to-platform>'
    #     local_path_provisioner_helm_chart:
    #       repo:
    #         enable: <true/false-defaults-to-true>
    #         repo_name: '<replace-with-helm-repo-name-defaults-to-containeroo>'
    #         repo_url: '<replace-with-app-chart-helm-repo-url-defaults-to-https://charts.containeroo.ch>'
    #         chart_name: '<replace-with-app-chart-name-defaults-to-local-path-provisioner>'
    #         chart_version: '<replace-with-chart-version-defaults-to-0.0.32>'
    #         release_name: '<replace-with-release-name-for-helm-deploy-defaults-to-local-path-provisioner>'
    #         user_value_override_files: ['list-of-absolute-path-of-value-override-files']
    #         k8s_namespace: '<replace-with-k8s-namespace-for-local_path_provisioner-chart-to-deploy-defaults-to-platform>'
    #     observability_helm_chart:
    #       repo:
    #         enable: <true/false-defaults-to-true>
    #         repo_name: '<replace-with-helm-repo-name-defaults-to-nvidia-ace>'
    #         repo_url: '<replace-with-app-chart-helm-repo-url-defaults-to-https://helm.ngc.nvidia.com/nvidia/ace>'
    #         chart_name: '<replace-with-app-chart-name-defaults-to-ucf-foundational-chart-observability-stack>'
    #         chart_version: '<replace-with-chart-version-defaults-to-0.0.6>'
    #         release_name: '<replace-with-release-name-for-helm-deploy-defaults-to-observability>'
    #         user_value_override_files: ['list-of-absolute-path-of-value-override-files']
    #         k8s_namespace: '<replace-with-k8s-namespace-for-observability-chart-to-deploy-defaults-to-platform>'
    secrets:
      ngc_cli_api_key: "{{ lookup('env', 'NGC_CLI_API_KEY', default=Undefined) }}"
  app:
    configs:
      app_settings:
        # k8s_namespace: '<replace-with-k8s-namespace-for-app-chart-to-deploy-defaults-to-app>'
        # helm_chart:
        #   repo:
        #     enable: <true/false-defaults-to-true>
        #     repo_url: '<replace-with-app-chart-helm-repo-url-defaults-to-https://helm.ngc.nvidia.com/nvidia/ace>'
        #     chart_name: '<replace-with-app-chart-name-defaults-to-tokkio-1stream-with-ui>'
        #     chart_version: '<replace-with-chart-version-defaults-to-5.0.0-GA>'
        #     release_name: '<replace-with-release-name-for-helm-deploy-defaults-to-tokkio-app>'
        #     user_value_override_files: ['list-of-absolute-path-of-value-override-files']
        #   local:
        #      enable: <true/false-defaults-to-false>
        #      path: '<absolute-path-of-helm-chart-present-locally>'
        #      release_name: '<replace-with-release-name-for-helm-deploy-defaults-to-tokkio-app>'
        #      user_value_override_files: ['list-of-absolute-path-of-value-override-files']
        k8s_secrets:
          - name: 'ngc-api-key-secret'
            type: 'Opaque'
            entries:
              - key: NGC_CLI_API_KEY
                value: "{{ lookup('env', 'NGC_CLI_API_KEY', default=Undefined) }}"
          - name: 'openai-key-secret'
            type: 'Opaque'
            entries:
              - key: OPENAI_API_KEY
                value: "{{ lookup('env', 'OPENAI_API_KEY', default=Undefined) }}"
          - name: 'nvidia-api-key-secret'
            type: 'Opaque'
            entries:
              - key: NVIDIA_API_KEY
                value: "{{ lookup('env', 'NVIDIA_API_KEY', default=Undefined) }}"
          - name: 'ngc-docker-reg-secret'
            type: 'dockerconfigjson'
            registry_name: "nvcr.io"
            username: '$oauthtoken'
            password: "{{ lookup('env', 'NGC_CLI_API_KEY', default=Undefined) }}"
          - name: 'elevenlabs-api-key-secret'
            type: 'Opaque'
            entries:
              - key: ELEVENLABS_API_KEY
                value: "{{ lookup('env', 'ELEVENLABS_API_KEY', default=Undefined) }}"
      # turn_server_settings:
        # # NOTE: Uncomment and update below section - coturn_settings in case turn_server_provider = coturn
        # coturn:
        #   username: '<replace-with-a-username-to-use-for-the-turnserver-defaults-to-foo>'
        #   password: '<replace-with-a-password-to-use-for-the-turnserver-defaults-to-bar>'
        #   realm: '<replace-with-a-realm-to-use-for-the-turnserver-defaults-to-mydummyt.org>'
        # # NOTE: # Uncomment and pass correct value for account_sid & auth_token for account_sid & account_sid  when turn_server_provider = twilio.
        # twilio:
        #   account_sid: '<replace-with-correct-twilio-account_sid-value-defaults-to-empty-string>'
        #   auth_token: '<replace-with-correct-twilio-auth_token-value-defailts-to-empty-string>'
    secrets:
      ngc_cli_api_key: "{{ lookup('env', 'NGC_CLI_API_KEY', default=Undefined) }}"
