# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Parameters related to the face
face_parameters:
  # Controls the range of motion on the upper regions of the face
  upperFaceStrength: 1
  # Applies temporal smoothing to the upper face motion
  upperFaceSmoothing: 0.001
  # Controls the range of motion on the lower regions of the face1
  lowerFaceStrength: 1.25
  # Applies temporal smoothing to the lower face motion
  lowerFaceSmoothing: 0.006
  # Determines the boundary between the upper and lower regions of the face
  faceMaskLevel: 0.6
  # Determines how smoothly the upper and lower face regions blend on the boundary
  faceMaskSoftness: 0.0085
  # Controls the range of motion of the skin
  skinStrength: 1
  # Adjusts the default pose of eyelid open-close
  eyelidOpenOffset: 0.0
  # Adjusts the default pose of lip close-open
  lipOpenOffset: 0.0

# contains multipliers and offsets to be applied on the inference result
# For more information about blendshapes see:
# https://developer.apple.com/documentation/arkit/arfaceanchor/blendshapelocation
blendshape_parameters:
  multipliers:
    EyeBlinkLeft: 1.0
    EyeLookDownLeft: 0.0
    EyeLookInLeft: 0.0
    EyeLookOutLeft: 0.0
    EyeLookUpLeft: 0.0
    EyeSquintLeft: 1.0
    EyeWideLeft: 1.0
    EyeBlinkRight: 1.0
    EyeLookDownRight: 0.0
    EyeLookInRight: 0.0
    EyeLookOutRight: 0.0
    EyeLookUpRight: 0.0
    EyeSquintRight: 1.0
    EyeWideRight: 1.0
    JawForward: 0.7
    JawLeft: 0.2
    JawRight: 0.2
    JawOpen: 1.0
    MouthClose: 0.0
    MouthFunnel: 1.0
    MouthPucker: 1.0
    MouthLeft: 0.2
    MouthRight: 0.2
    MouthSmileLeft: 0.7
    MouthSmileRight: 0.7
    MouthFrownLeft: 0.5
    MouthFrownRight: 0.5
    MouthDimpleLeft: 0.5
    MouthDimpleRight: 0.5
    MouthStretchLeft: 0.2
    MouthStretchRight: 0.2
    MouthRollLower: 0.6
    MouthRollUpper: 0.4
    MouthShrugLower: 0.7
    MouthShrugUpper: 0.4
    MouthPressLeft: 0.8
    MouthPressRight: 0.8
    MouthLowerDownLeft: 0.8
    MouthLowerDownRight: 0.8
    MouthUpperUpLeft: 0.8
    MouthUpperUpRight: 0.8
    BrowDownLeft: 1.0
    BrowDownRight: 1.0
    BrowInnerUp: 1.0
    BrowOuterUpLeft: 1.0
    BrowOuterUpRight: 1.0
    CheekPuff: 0.2
    CheekSquintLeft: 1.0
    CheekSquintRight: 1.0
    NoseSneerLeft: 0.8
    NoseSneerRight: 0.8
    TongueOut: 0.0
  offsets:
    EyeBlinkLeft: 0.0
    EyeLookDownLeft: 0.0
    EyeLookInLeft: 0.0
    EyeLookOutLeft: 0.0
    EyeLookUpLeft: 0.0
    EyeSquintLeft: 0.0
    EyeWideLeft: 0.0
    EyeBlinkRight: 0.0
    EyeLookDownRight: 0.0
    EyeLookInRight: 0.0
    EyeLookOutRight: 0.0
    EyeLookUpRight: 0.0
    EyeSquintRight: 0.0
    EyeWideRight: 0.0
    JawForward: 0.0
    JawLeft: 0.0
    JawRight: 0.0
    JawOpen: 0.0
    MouthClose: 0.0
    MouthFunnel: 0.0
    MouthPucker: 0.0
    MouthLeft: 0.0
    MouthRight: 0.0
    MouthSmileLeft: 0.0
    MouthSmileRight: 0.0
    MouthFrownLeft: 0.0
    MouthFrownRight: 0.0
    MouthDimpleLeft: 0.0
    MouthDimpleRight: 0.0
    MouthStretchLeft: 0.0
    MouthStretchRight: 0.0
    MouthRollLower: 0.0
    MouthRollUpper: 0.0
    MouthShrugLower: 0.0
    MouthShrugUpper: 0.0
    MouthPressLeft: 0.0
    MouthPressRight: 0.0
    MouthLowerDownLeft: 0.0
    MouthLowerDownRight: 0.0
    MouthUpperUpLeft: 0.0
    MouthUpperUpRight: 0.0
    BrowDownLeft: 0.0
    BrowDownRight: 0.0
    BrowInnerUp: 0.0
    BrowOuterUpLeft: 0.0
    BrowOuterUpRight: 0.0
    CheekPuff: 0.0
    CheekSquintLeft: 0.0
    CheekSquintRight: 0.0
    NoseSneerLeft: 0.0
    NoseSneerRight: 0.0
    TongueOut: 0.0

# Parameters related to the post-processing of emotions.
post_processing_parameters:
  # Increases the spread between emotion values by pushing them higher or lower
  emotion_contrast: 1.0
  # Coefficient for smoothing emotions over time
  live_blend_coef: 0.7
  # Tells the A2F pipeline whether to use emotions weights defined under this sections
  enable_preferred_emotion: true
  # Sets the strength of the preferred emotion (if is loaded) relative to generated emotions
  preferred_emotion_strength: 0.5
  # Sets the strength of emotions relative to neutral emotion
  emotion_strength: 0.6
  # Sets a firm limit on the quantity of emotion sliders engaged by A2E - emotions with highest weight will be prioritized
  max_emotions: 3

# Manual emotion input
# Here there is a list of `emotion with timecode`
# You can add more of them if needed.
# An emotion with timecode is an emotion that is applied at a specific timecode
# Emotions must be between 0.0 and 1.0
# Timecodes must be >= 0.0
emotion_with_timecode_list:
  # this first emotion with timecode will apply joy at the very beginning of the
  # audio clip
  emotion_with_timecode1:
      time_code: 0.0
      emotions:
        amazement: 0.0
        anger: 0.0
        cheekiness: 0.0
        disgust: 0.0
        fear: 0.0
        grief: 0.0
        joy: 1.0
        outofbreath: 0.0
        pain: 0.0
        sadness: 0.0
  # this second emotion with timecode will apply fear after 1 second of audio in the
  # audio clip
  emotion_with_timecode2:
      time_code: 1.0
      emotions:
        amazement: 0.0
        anger: 0.0
        cheekiness: 0.0
        disgust: 0.0
        fear: 1.0
        grief: 0.0
        joy: 0.0
        outofbreath: 0.0
        pain: 0.0
        sadness: 0.0
