bot: food_ordering

configs:
  enable_intent_slot: True

# Using OpenAI
models:
  - type: main
    engine: openai
    model: gpt-3.5-turbo-instruct
    parameters:
      stop: ["\n"]

nlp_models:
  - task_name: generate_user_intent
    model_name: riva_intent_drive_thru
    confidence_threshold: 0.5