grpc_server:
  nvidia::rrt::BotRuntimeGrpc: # component type
    ip_address: "0.0.0.0"
    port_number: 50055
    virtual_assistant_num_instances: 30
    virtual_assistant_pipeline_idle_threshold_secs: 600
    virtual_assistant_pipeline_idle_handler_wakeup_rate_secs: 10

speech_pipeline_manager: # config name
  SpeechPipelineManager: # component name
    asr_idle_timeout_ms: 200000
    tts_eos_delay_ms: 2000

riva_asr:
  RivaASR:
    server: "localhost:50051"
    word_boost_file_path: "/workspace/config/asr_words_to_boost.txt"
    enable_profanity_filter: false

dialog_manager:
  DialogManager:
    server: "http://localhost:9002/langgraph"
    use_streaming: true

riva_tts:
  RivaTTS:
    server: "localhost:50051"
    voice_name: "English-US-RadTTS.Female-1"
    language: "en-US"
    ipa_dict: ""
    sample_rate: 44100

riva_logger:
  RivaLogger:
    data_dump_path: "/workspace/log"
    enable_logging: true