---
- hosts: all
  gather_facts: yes
  tasks:
  - name: install k8s secret of type Opaque
    loop: "{{ task_config.k8s_secrets }}"
    when: item.type == "Opaque"
    include_tasks: k8s-secret-opaque.yml


  - name: Install k8s secret of type dockerconfigjson
    loop: "{{ task_config.k8s_secrets }}"
    when: item.type == "dockerconfigjson"
    include_tasks: k8s-secret-dockerconfig.yml
