---
- hosts: all
  gather_facts: yes
  tasks:
    - name: check if k8s secrets are empty of type Opaque
      loop: "{{ task_config.k8s_secrets }}"
      when: item.type == "Opaque"
      include_tasks: k8s-secret-check-empty-opaque.yml

    - name: check if k8s secrets are empty of type dockerconfigjson
      loop: "{{ task_config.k8s_secrets }}"
      when: item.type == "dockerconfigjson"
      include_tasks: k8s-secret-check-empty-dockerconfig.yml
