---
- hosts: all
  gather_facts: yes
  tasks: []
- hosts: master
  gather_facts: no
  tasks:
  - name: prepare node taints
    set_fact:
      node_taints: "{{ node_taints | default({}) | combine( {hostvars[item.key].ansible_facts.hostname: item.value} ) }}"
    with_dict: "{{ task_config.node_taints }}"
  - name: apply node taints
    kubernetes.core.k8s_taint:
      kubeconfig: "{{ task_config.kubeconfig | default(omit) }}"
      state: "{{ state | default('present') }}"
      name: "{{ item.key }}"
      taints: "{{ item.value if item.value is defined else [] }}"
    with_dict: "{{ node_taints }}"