specVersion: 2.5.0

version: 4.0.0

name: ucf-app-speech-bot

description: ACE Agent Stock Bot UCS Application

dependencies:
- ucf.svc.riva.speech-skills:2.15.1
- ucf.svc.ace-agent.chat-engine:4.0.0
- ucf.svc.ace-agent.chat-controller:4.0.0
- ucf.svc.ace-agent.plugin-server:4.0.0
- ucf.svc.ace-agent.web-app:4.0.0

secrets:
  k8sSecret/ngc-api-key-secret/NGC_CLI_API_KEY:
    k8sSecret:
      secretName: ngc-api-key-secret
      key: NGC_CLI_API_KEY
  k8sSecret/custom-env-secrets:
    k8sSecret:
      secretName: custom-env-secrets
      key: ENV
components:
- name: webapp
  type: ucf.svc.ace-agent.web-app
  parameters:
    imagePullSecrets:
    - name: ngc-docker-reg-secret
- name: riva-speech
  type: ucf.svc.riva.speech-skills
  parameters:
    imagePullSecrets:
    - name: ngc-docker-reg-secret
  secrets:
    ngc-api-key-secret: k8sSecret/ngc-api-key-secret/NGC_CLI_API_KEY
- name: chat-engine
  type: ucf.svc.ace-agent.chat-engine
  parameters:
    imagePullSecrets:
    - name: ngc-docker-reg-secret
  secrets:
    ngc-api-key-secret: k8sSecret/ngc-api-key-secret/NGC_CLI_API_KEY
    custom-env-secrets: k8sSecret/custom-env-secrets
  files:
    config_dir: ../../../../samples/stock_bot
- name: chat-controller
  type: ucf.svc.ace-agent.chat-controller
  parameters:
    imagePullSecrets:
    - name: ngc-docker-reg-secret
  secrets:
    ngc-api-key-secret: k8sSecret/ngc-api-key-secret/NGC_CLI_API_KEY
  files:
    config_dir: ../../../../samples/stock_bot
- name: plugin-server
  type: ucf.svc.ace-agent.plugin-server
  parameters:
    imagePullSecrets:
    - name: ngc-docker-reg-secret
  secrets:
    ngc-api-key-secret: k8sSecret/ngc-api-key-secret/NGC_CLI_API_KEY
  files:
    config_dir: ../../../../samples/stock_bot


connections:
  chat-engine/plugin-server: plugin-server/http-api
  chat-controller/riva: riva-speech/riva-speech-api
  chat-controller/chat-api: chat-engine/http-api
  webapp/chat-controller: chat-controller/grpc-api
