- hosts: all
  gather_facts: yes
  become: false
  tasks:
    - name: Fail if variable is empty
      fail:
        msg: "The variable 'item.key' is empty. Please provide a valid value."
      when: my_var | length == 0
      loop: "{{ task_vars }}"
