schema_version: '0.0.10'
name: '<replace-with-unique-deployment-name>'
spec:
  infra:
    csp: 'gcp'
    backend:
      bucket: '<replace-with-deployment-state-bucket-name>'
      credentials: "{{ lookup('env', 'CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE', default=Undefined) }}"
    provider:
      project: "{{ lookup('env', 'CLOUDSDK_CORE_PROJECT', default=Undefined) }}"
      credentials: "{{ lookup('env', 'CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE', default=Undefined) }}"
    configs:
      cns:
        override_values:
          cns_nvidia_driver: yes
      user_access_cidrs:
        - '<replace-with-cidr-from-where-application-ui-and-api-is-accessed>'
      dev_access_cidrs:
        - '<replace-with-cidr-from-where-infra-is-accessed-using-ssh>'
      region: '<replace-with-resources-deployment-region>'
      ui_bucket_location:
        location: 'replace-with-bucket-location-used-for-hosting-static-ui'
        region: 'replace-with-bucket-region'
        alternate_region: 'replace-with-bucket-alternate-region'
      ssh_public_key: "{{ lookup('file', lookup('env', 'HOME') + '<replace-with-relative-path-of-public-ssh-key-w.r.t.-user-home-directory>') }}"
      ssh_private_key_path: "{{ lookup('env', 'HOME') + '<replace-with-relative-path-of-private-ssh-key-w.r.t.-user-home-directory>' }}"
      dns_zone_name: '<replace-with-your-base-domain>'
      enable_cdn: false
      clusters:
        app:
          private_instance: true
          master:
            type: 'g2-standard-48'
            guest_accelerators:
            - type: 'nvidia-l4'
              count: '4'
          features:
            cns: true
            app: true
        turn:
          private_instance: false
          master:
            type: 'e2-medium'
            guest_accelerators: []
          features:
            coturn: true
  platform:
    secrets:
      ngc_cli_api_key: "{{ lookup('env', 'NGC_CLI_API_KEY', default=Undefined) }}"
  app:
    configs:
      app_settings:
        k8s_secrets:
          - name: 'ngc-api-key-secret'
            type: 'Opaque'
            entries:
              - key: NGC_CLI_API_KEY
                value: "{{ lookup('env', 'NGC_CLI_API_KEY', default=Undefined) }}"
          - name: 'openai-key-secret'
            type: 'Opaque'
            entries:
              - key: OPENAI_API_KEY
                value: "{{ lookup('env', 'OPENAI_API_KEY', default=Undefined) }}"
          - name: 'nvidia-api-key-secret'
            type: 'Opaque'
            entries:
              - key: NVIDIA_API_KEY
                value: "{{ lookup('env', 'NVIDIA_API_KEY', default=Undefined) }}"
          - name: 'ngc-docker-reg-secret'
            type: 'dockerconfigjson'
            registry_name: "nvcr.io"
            username: '$oauthtoken'
            password: "{{ lookup('env', 'NGC_CLI_API_KEY', default=Undefined) }}"
          - name: 'elevenlabs-api-key-secret'
            type: 'Opaque'
            entries:
              - key: ELEVENLABS_API_KEY
                value: "{{ lookup('env', 'ELEVENLABS_API_KEY', default=Undefined) }}"
    secrets:
      ngc_cli_api_key: "{{ lookup('env', 'NGC_CLI_API_KEY', default=Undefined) }}"
