module "rp_instance" {
  for_each                = toset(var.instance_suffixes)
  source                  = "../../gcp/instance"
  name                    = local.instance_config.name
  region                  = local.instance_config.region
  zone                    = local.instance_config.zone
  network                 = local.instance_config.network
  subnetwork              = local.instance_config.subnetwork
  static_public_ip        = local.instance_config.static_public_ip
  network_interface       = local.instance_config.network_interface
  tags                    = local.instance_config.tags
  machine_type            = local.instance_config.machine_type
  service_account_email   = google_service_account.service_account.email
  service_account_scopes  = local.instance_config.service_account_scopes
  boot_disk               = local.instance_config.boot_disk
  data_disks              = local.instance_config.data_disks
  ssh_public_key          = local.instance_config.ssh_public_key
  ssh_user                = local.instance_config.ssh_user
  metadata_startup_script = local.instance_config.metadata_startup_script
}