specVersion: 2.5.0

version: 4.1.0

name: ucf-app-speech-bot

description: ACE Agent Food Ordering Bot

dependencies:
- ucf.svc.riva.speech-skills:2.17.0
- ucf.svc.ace-agent.chat-engine:4.1.0
- ucf.svc.ace-agent.chat-controller:4.1.0
- ucf.svc.ace-agent.plugin-server:4.1.0
- ucf.svc.ace-agent.web-app:4.1.0
- ucf.svc.ace-agent.nlp-server:4.1.0
- ucf.svc.core.redis-timeseries:0.0.20

secrets:
  k8sSecret/ngc-api-key-secret/NGC_CLI_API_KEY:
    k8sSecret:
      secretName: ngc-api-key-secret
      key: NGC_CLI_API_KEY
  k8sSecret/openai-key-secret/OPENAI_API_KEY:
    k8sSecret:
      secretName: openai-key-secret
      key: OPENAI_API_KEY

components:
- name: webapp
  type: ucf.svc.ace-agent.web-app
  parameters:
    imagePullSecrets:
    - name: ngc-docker-reg-secret
- name: redis-timeseries
  type: ucf.svc.core.redis-timeseries
  parameters:
    imagePullSecrets:
    - name: ngc-docker-reg-secret
- name: riva-speech
  type: ucf.svc.riva.speech-skills
  parameters:
    imagePullSecrets:
    - name: ngc-docker-reg-secret
  secrets:
    ngc-api-key-secret: k8sSecret/ngc-api-key-secret/NGC_CLI_API_KEY
- name: nlp-server
  type: ucf.svc.ace-agent.nlp-server
  parameters:
    imagePullSecrets:
    - name: ngc-docker-reg-secret
  secrets:
    ngc-api-key-secret: k8sSecret/ngc-api-key-secret/NGC_CLI_API_KEY
  files:
    config_dir: ../../../../samples/food_ordering_bot
- name: chat-engine
  type: ucf.svc.ace-agent.chat-engine
  parameters:
    imagePullSecrets:
    - name: ngc-docker-reg-secret
  secrets:
    ngc-api-key-secret: k8sSecret/ngc-api-key-secret/NGC_CLI_API_KEY
    openai-key-secret: k8sSecret/openai-key-secret/OPENAI_API_KEY
  files:
    config_dir: ../../../../samples/food_ordering_bot
- name: chat-controller
  type: ucf.svc.ace-agent.chat-controller
  parameters:
    imagePullSecrets:
    - name: ngc-docker-reg-secret
  secrets:
    ngc-api-key-secret: k8sSecret/ngc-api-key-secret/NGC_CLI_API_KEY
  files:
    config_dir: ../../../../samples/food_ordering_bot
- name: plugin-server
  type: ucf.svc.ace-agent.plugin-server
  parameters:
    imagePullSecrets:
    - name: ngc-docker-reg-secret
  secrets:
    ngc-api-key-secret: k8sSecret/ngc-api-key-secret/NGC_CLI_API_KEY
  files:
    config_dir: ../../../../samples/food_ordering_bot


connections:
  chat-engine/plugin-server: plugin-server/http-api
  chat-engine/nlp-server: nlp-server/api-server
  chat-engine/redis: redis-timeseries/redis
  chat-controller/redis: redis-timeseries/redis
  chat-controller/riva: riva-speech/riva-speech-api
  webapp/chat-controller: chat-controller/grpc-api
  webapp/redis: redis-timeseries/redis
