chat-controller:
  pipeline: speech_umim
  speechConfigPath: "speech_config.yaml"
  pipelineParams: # can be extended for all pipeline params in speech_config.yaml
    grpc_server:
      nvidia::rrt::BotRuntimeGrpc:
        virtual_assistant_num_instances: 30

chat-engine:
  botConfigName: colang_2_sample_bot_config.yml
  interface: event
  gunicornWorkers: "4"

riva-speech:
  riva:
    visibleGpus: "0"
  modelRepoGenerator:
    clearAllRMIRSAndModels: false
    #> description: Flag to clear artifacts and models before downloading and deploying
    ngcModelConfigs:
      triton0:
        models:
        #> description: List of NGC models for deployment
        - nvidia/ucs-ms/rmir_asr_parakeet_1-1b_en_us_str_vad:2.15.0 #english
        - nvidia/riva/rmir_tts_radtts_hifigan_en_us_ipa:2.15.0
  persistentVolumeClaim:
    keepPVC: True
