specVersion: 2.5.0

version: 4.0.0

name: ucf-app-speech-bot

description: ACE Agent Food Ordering Bot

dependencies:
- ucf.svc.riva.speech-skills:2.15.1
- ucf.svc.ace-agent.chat-engine:4.0.0
- ucf.svc.ace-agent.chat-controller:4.0.0
- ucf.svc.core.redis-timeseries:0.0.19

secrets:
  k8sSecret/ngc-api-key-secret/NGC_CLI_API_KEY:
    k8sSecret:
      secretName: ngc-api-key-secret
      key: NGC_CLI_API_KEY
  k8sSecret/openai-key-secret/OPENAI_API_KEY:
    k8sSecret:
      secretName: openai-key-secret
      key: OPENAI_API_KEY

components:
- name: riva-speech
  type: ucf.svc.riva.speech-skills
  parameters:
    imagePullSecrets:
    - name: ngc-docker-reg-secret
  secrets:
    ngc-api-key-secret: k8sSecret/ngc-api-key-secret/NGC_CLI_API_KEY
- name: chat-engine
  type: ucf.svc.ace-agent.chat-engine
  parameters:
    imagePullSecrets:
    - name: ngc-docker-reg-secret
  secrets:
    ngc-api-key-secret: k8sSecret/ngc-api-key-secret/NGC_CLI_API_KEY
    openai-key-secret: k8sSecret/openai-key-secret/OPENAI_API_KEY
  files:
    config_dir: ../../../../samples/colang_2_sample_bot
- name: chat-controller
  type: ucf.svc.ace-agent.chat-controller
  parameters:
    imagePullSecrets:
    - name: ngc-docker-reg-secret
  secrets:
    ngc-api-key-secret: k8sSecret/ngc-api-key-secret/NGC_CLI_API_KEY
  files:
    config_dir: ../../../../samples/colang_2_sample_bot
- name: redis-timeseries
  type: ucf.svc.core.redis-timeseries
  parameters:
    imagePullSecrets:
    - name: ngc-docker-reg-secret

connections:
  chat-engine/redis: redis-timeseries/redis
  chat-controller/redis: redis-timeseries/redis
  chat-controller/riva: riva-speech/riva-speech-api
  chat-controller/chat-api: chat-engine/http-api
