chat-controller:
  pipeline: speech_umim
  speechConfigPath: "jin/speech_config.yaml"

riva-speech:
  riva:
    visibleGpus: "0"
  modelRepoGenerator:
    clearAllRMIRSAndModels: false
    #> description: Flag to clear artifacts and models before downloading and deploying
    ngcModelConfigs:
      triton0:
        models:
        #> description: List of NGC models or Bot Config for deployment
        - nvidia/ace/rmir_asr_parakeet_1-1b_en_us_str_vad:2.17.0
        - nvidia/riva/rmir_tts_fastpitch_hifigan_en_us_ipa:2.17.0
  persistentVolumeClaim:
    keepPVC: True

chat-engine:
  botConfigName: jin/bot_config.yaml
  interface: event

plugin-server:
  pluginConfigPath: "jin/plugin_config.yaml"

webapp:
  chatInterface: "event"
  speechFlags: "--speech"