---
- hosts: all
  gather_facts: yes
  tasks:
  - name: install secret
    kubernetes.core.k8s:
      kubeconfig: "{{ task_config.kubeconfig | default(omit) }}"
      state: "{{ state | default('present') }}"
      definition:
        apiVersion: v1
        kind: Secret
        type: "{{ task_config.type }}"
        metadata:
          name: "{{ task_config.name }}"
          namespace: "{{ task_config.namespace | default('default') }}"
        data:
          "{{ task_config.data }}"
