    - name: create secret_data variable 
      set_fact:
        secret_data: |
          {% set result = {} %}
          {%- for element in item.entries -%}
          {% set _ = result.update({element.key: element.value | b64encode}) %}
          {%- endfor -%}
          {{ result }}

    # - name: Debug secret data
    #   debug:
    #     msg: "{{ secret_data }}"

    - name: Create Kubernetes secrets of type Opaque
      kubernetes.core.k8s:
        kubeconfig: "{{ item.kubeconfig | default(omit) }}"
        state: "{{ state | default('present') }}"
        definition:
          api_version: v1
          kind: Secret
          type: "{{ item.type }}"
          metadata:
            name: "{{ item.name }}"
            namespace: "{{ task_config.namespace | default('default') }}"
          data: "{{ secret_data }}"