  - name: Concatenate username and password
    set_fact:
      combined_string: "{{ item.username }}:{{ item.password }}"
  - name: Encode concatenated string to Base64
    set_fact:
      encoded_credentials: "{{ combined_string | b64encode }}"
  - name: create dockerconfigjson
    set_fact:
      dockerconfigjson: |
          {
            "auths": {
              "{{ item.registry_name }}": {
                "auth": "{{ encoded_credentials }}"
              }
            }
          }
  - name: encode dockerconfigjson
    set_fact:
      encode_dockerconfigjson: "{{ dockerconfigjson | to_json | b64encode }}"
  # - name: display
  #   debug:
  #     msg: "{{ encode_dockerconfigjson }}"
  - name: install k8s secret of type dockerconfigjson
    kubernetes.core.k8s:
      kubeconfig: "{{ item.kubeconfig | default(omit) }}"
      state: "{{ state | default('present') }}"
      definition:
        apiVersion: v1
        kind: Secret
        type: "kubernetes.io/{{ item.type }}"
        metadata:
          name: "{{ item.name }}"
          namespace: "{{ task_config.namespace | default('default') }}"
        data:
          .dockerconfigjson: "{{ encode_dockerconfigjson }}"
